# Generated by Django 4.0.1 on 2022-01-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codinst', models.CharField(blank=True, max_length=20, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigomunicipio', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('calendario', models.CharField(blank=True, max_length=2, null=True)),
                ('naturaleza', models.CharField(blank=True, max_length=30, null=True)),
                ('evaluados', models.IntegerField(blank=True, null=True)),
                ('matematicas', models.FloatField(blank=True, null=True)),
                ('sociales', models.FloatField(blank=True, null=True)),
                ('ingles', models.FloatField(blank=True, null=True)),
                ('ciencias', models.FloatField(blank=True, null=True)),
                ('lectura', models.FloatField(blank=True, null=True)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('promponderado', models.FloatField(blank=True, null=True)),
                ('puntajeglobal', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio2020',
            fields=[
                ('colegio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='visor.colegio')),
            ],
            options={
                'db_table': 'saber2020A',
            },
            bases=('visor.colegio',),
        ),
    ]
