# Generated by Django 4.0.1 on 2022-01-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colegio2020',
        ),
    ]
