# Generated by Django 4.0.1 on 2022-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0002_delete_colegio2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=120)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
